server:
  port: 8735

spring:
  application:
    name: eureka-service-center-2

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}:${spring.application.name}
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://ums-eureka-1:8729/eureka/
#      defaultZone: http://${eureka.instance.hostname}:8729/eureka/
