server:
  port: 8734

spring:
  application:
    name: query-service
  datasource:
    url: jdbc:mysql://localhost:3306/service_enabling?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: service_enabling
    password: se8192
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootMybatisHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8729/eureka/

mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.springboot.mybatis.demo.mapper: debug